//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTest.AtIRCService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", ConfigurationName="AtIRCService.documentosTransporte")]
    public interface documentosTransporte {
        
        // CODEGEN: Generating message contract since the operation envioDocumentoTransporte is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="https://servicos.portaldasfinancas.gov.pt:701/sgdtws/documentosTransporte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SimpleTest.AtIRCService.envioDocumentoTransporteResponse envioDocumentoTransporte(SimpleTest.AtIRCService.envioDocumentoTransporteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://servicos.portaldasfinancas.gov.pt:701/sgdtws/documentosTransporte", ReplyAction="*")]
        System.Threading.Tasks.Task<SimpleTest.AtIRCService.envioDocumentoTransporteResponse> envioDocumentoTransporteAsync(SimpleTest.AtIRCService.envioDocumentoTransporteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public partial class StockMovement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string taxRegistrationNumberField;
        
        private string companyNameField;
        
        private AddressStructurePT companyAddressField;
        
        private string documentNumberField;
        
        private string aTDocCodeIDField;
        
        private MovementStatus movementStatusField;
        
        private System.DateTime movementDateField;
        
        private MovementType movementTypeField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private AddressStructurePT customerAddressField;
        
        private string customerNameField;
        
        private AddressStructurePT addressToField;
        
        private AddressStructurePT addressFromField;
        
        private System.DateTime movementEndTimeField;
        
        private bool movementEndTimeFieldSpecified;
        
        private System.DateTime movementStartTimeField;
        
        private string vehicleIDField;
        
        private Line[] lineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string TaxRegistrationNumber {
            get {
                return this.taxRegistrationNumberField;
            }
            set {
                this.taxRegistrationNumberField = value;
                this.RaisePropertyChanged("TaxRegistrationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public AddressStructurePT CompanyAddress {
            get {
                return this.companyAddressField;
            }
            set {
                this.companyAddressField = value;
                this.RaisePropertyChanged("CompanyAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
                this.RaisePropertyChanged("DocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ATDocCodeID {
            get {
                return this.aTDocCodeIDField;
            }
            set {
                this.aTDocCodeIDField = value;
                this.RaisePropertyChanged("ATDocCodeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public MovementStatus MovementStatus {
            get {
                return this.movementStatusField;
            }
            set {
                this.movementStatusField = value;
                this.RaisePropertyChanged("MovementStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=6)]
        public System.DateTime MovementDate {
            get {
                return this.movementDateField;
            }
            set {
                this.movementDateField = value;
                this.RaisePropertyChanged("MovementDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public MovementType MovementType {
            get {
                return this.movementTypeField;
            }
            set {
                this.movementTypeField = value;
                this.RaisePropertyChanged("MovementType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomerTaxID", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlElementAttribute("SupplierTaxID", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public AddressStructurePT CustomerAddress {
            get {
                return this.customerAddressField;
            }
            set {
                this.customerAddressField = value;
                this.RaisePropertyChanged("CustomerAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public AddressStructurePT AddressTo {
            get {
                return this.addressToField;
            }
            set {
                this.addressToField = value;
                this.RaisePropertyChanged("AddressTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public AddressStructurePT AddressFrom {
            get {
                return this.addressFromField;
            }
            set {
                this.addressFromField = value;
                this.RaisePropertyChanged("AddressFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public System.DateTime MovementEndTime {
            get {
                return this.movementEndTimeField;
            }
            set {
                this.movementEndTimeField = value;
                this.RaisePropertyChanged("MovementEndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MovementEndTimeSpecified {
            get {
                return this.movementEndTimeFieldSpecified;
            }
            set {
                this.movementEndTimeFieldSpecified = value;
                this.RaisePropertyChanged("MovementEndTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public System.DateTime MovementStartTime {
            get {
                return this.movementStartTimeField;
            }
            set {
                this.movementStartTimeField = value;
                this.RaisePropertyChanged("MovementStartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string VehicleID {
            get {
                return this.vehicleIDField;
            }
            set {
                this.vehicleIDField = value;
                this.RaisePropertyChanged("VehicleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public Line[] Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
                this.RaisePropertyChanged("Line");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public partial class AddressStructurePT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressdetailField;
        
        private string cityField;
        
        private string postalCodeField;
        
        private string countryField;
        
        public AddressStructurePT() {
            this.countryField = "PT";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Addressdetail {
            get {
                return this.addressdetailField;
            }
            set {
                this.addressdetailField = value;
                this.RaisePropertyChanged("Addressdetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public partial class ResponseStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("ReturnMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public partial class StockMovementResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseStatus[] responseStatusField;
        
        private string documentNumberField;
        
        private string aTDocCodeIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResponseStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponseStatus[] ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
                this.RaisePropertyChanged("ResponseStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
                this.RaisePropertyChanged("DocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ATDocCodeID {
            get {
                return this.aTDocCodeIDField;
            }
            set {
                this.aTDocCodeIDField = value;
                this.RaisePropertyChanged("ATDocCodeID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public partial class OrderReferences : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string originatingONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OriginatingON {
            get {
                return this.originatingONField;
            }
            set {
                this.originatingONField = value;
                this.RaisePropertyChanged("OriginatingON");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public partial class Line : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OrderReferences[] orderReferencesField;
        
        private string productDescriptionField;
        
        private decimal quantityField;
        
        private string unitOfMeasureField;
        
        private decimal unitPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderReferences", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OrderReferences[] OrderReferences {
            get {
                return this.orderReferencesField;
            }
            set {
                this.orderReferencesField = value;
                this.RaisePropertyChanged("OrderReferences");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProductDescription {
            get {
                return this.productDescriptionField;
            }
            set {
                this.productDescriptionField = value;
                this.RaisePropertyChanged("ProductDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UnitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
                this.RaisePropertyChanged("UnitOfMeasure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
                this.RaisePropertyChanged("UnitPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public enum MovementStatus {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        A,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public enum MovementType {
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        GT,
        
        /// <remarks/>
        GA,
        
        /// <remarks/>
        GC,
        
        /// <remarks/>
        GD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":CustomerTaxID")]
        CustomerTaxID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":SupplierTaxID")]
        SupplierTaxID,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class envioDocumentoTransporteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", Order=0)]
        public SimpleTest.AtIRCService.StockMovement envioDocumentoTransporteRequestElem;
        
        public envioDocumentoTransporteRequest() {
        }
        
        public envioDocumentoTransporteRequest(SimpleTest.AtIRCService.StockMovement envioDocumentoTransporteRequestElem) {
            this.envioDocumentoTransporteRequestElem = envioDocumentoTransporteRequestElem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class envioDocumentoTransporteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", Order=0)]
        public SimpleTest.AtIRCService.StockMovementResponse envioDocumentoTransporteResponseElem;
        
        public envioDocumentoTransporteResponse() {
        }
        
        public envioDocumentoTransporteResponse(SimpleTest.AtIRCService.StockMovementResponse envioDocumentoTransporteResponseElem) {
            this.envioDocumentoTransporteResponseElem = envioDocumentoTransporteResponseElem;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface documentosTransporteChannel : SimpleTest.AtIRCService.documentosTransporte, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class documentosTransporteClient : System.ServiceModel.ClientBase<SimpleTest.AtIRCService.documentosTransporte>, SimpleTest.AtIRCService.documentosTransporte {
        
        public documentosTransporteClient() {
        }
        
        public documentosTransporteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public documentosTransporteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public documentosTransporteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public documentosTransporteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpleTest.AtIRCService.envioDocumentoTransporteResponse SimpleTest.AtIRCService.documentosTransporte.envioDocumentoTransporte(SimpleTest.AtIRCService.envioDocumentoTransporteRequest request) {
            return base.Channel.envioDocumentoTransporte(request);
        }
        
        public SimpleTest.AtIRCService.StockMovementResponse envioDocumentoTransporte(SimpleTest.AtIRCService.StockMovement envioDocumentoTransporteRequestElem) {
            SimpleTest.AtIRCService.envioDocumentoTransporteRequest inValue = new SimpleTest.AtIRCService.envioDocumentoTransporteRequest();
            inValue.envioDocumentoTransporteRequestElem = envioDocumentoTransporteRequestElem;
            SimpleTest.AtIRCService.envioDocumentoTransporteResponse retVal = ((SimpleTest.AtIRCService.documentosTransporte)(this)).envioDocumentoTransporte(inValue);
            return retVal.envioDocumentoTransporteResponseElem;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimpleTest.AtIRCService.envioDocumentoTransporteResponse> SimpleTest.AtIRCService.documentosTransporte.envioDocumentoTransporteAsync(SimpleTest.AtIRCService.envioDocumentoTransporteRequest request) {
            return base.Channel.envioDocumentoTransporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimpleTest.AtIRCService.envioDocumentoTransporteResponse> envioDocumentoTransporteAsync(SimpleTest.AtIRCService.StockMovement envioDocumentoTransporteRequestElem) {
            SimpleTest.AtIRCService.envioDocumentoTransporteRequest inValue = new SimpleTest.AtIRCService.envioDocumentoTransporteRequest();
            inValue.envioDocumentoTransporteRequestElem = envioDocumentoTransporteRequestElem;
            return ((SimpleTest.AtIRCService.documentosTransporte)(this)).envioDocumentoTransporteAsync(inValue);
        }
    }
}
